const Data=[
    {
        id:1,
        category:'Laptops',
        title: "Lenovo",
        imgsrc: "https://m.media-amazon.com/images/I/71AaHBtQhiL._SL1500_.jpg",
        amazonlink: "https://www.amazon.com/dp/B08L8NGB6S",
        description: "LENOVO LAPTOP",
        price:'39999',
      },
      { id:2,
        category:'Mobiles',
        title: "Apple iPhone 13",
        imgsrc: "https://m.media-amazon.com/images/I/71gm8v4uPBL._SX679_.jpg",
        amazonlink: "https://www.amazon.com/dp/B08L8NGB6S",
        description: "Apple iPhone 13 (128GB) - (Product) RED",
        price:'49999',
      },
      {
        id:3,
        category:'Mobiles',
        title: "Apple iphone 13 mini",
        imgsrc: "https://m.media-amazon.com/images/I/71657TiFeHL._SL1500_.jpg",
        amazonlink: "https://www.amazon.com/dp/B08L8NGB6S",
        description: "Apple iPhone 13 Mini (256 GB) - Green",
        price:'39999',
      },
      {
        id:9,
        category:'Mobiles',
        title: "Apple iphone 14",
        imgsrc: "https://m.media-amazon.com/images/I/61bK6PMOC3L._SL1500_.jpg",
        amazonlink: "https://www.amazon.com/dp/B08L8NGB6S",
        description: "Apple iPhone 14 (128 GB) - Blue",
        price:'69999',
      },
      { id:4,
        category:'Laptops',
        title: "Lenovo IDEAPAD",
        imgsrc: "https://m.media-amazon.com/images/I/41jlazl7-VL._SY300_SX300_QL70_FMwebp_.jpg",
        amazonlink: "https://www.amazon.com/dp/B08L8NGB6S",
        description: "IDEPAD",
        price:'49999',
      },
      {
      id:5,
      category:'Laptops',
      title: "HP 15 laptop",
      imgsrc: "https://m.media-amazon.com/images/I/71p8u7Upw1L._SL1500_.jpg",
      amazonlink: "https://www.amazon.com/dp/B08L8NGB6S",
      description: "Laptop, Intel Iris Xe Graphics, HD Camera",
      price:'59999',
      },
      {
        id:6,
        category:'Tablets',
        title: "REDMI PAD PRO 5G",
        imgsrc: "https://m.media-amazon.com/images/I/71jH01R-CgL._SL1500_.jpg",
        amazonlink:"https://www.amazon.com/dp/B08L8NGB6S",
        description: "Dark",
        price:'39999',
        },
        {
            id:7,
            category:'Tablets',
            title: "XIAMOI ",
            imgsrc: "https://m.media-amazon.com/images/I/61goypdjAYL._SL1500_.jpg",
            amazonlink: "https://www.amazon.com/dp/B08L8NGB6S",
            description: "XIAMOI PAD 7",
            price:'49999',
            },
            {
                id:8,
                category:'Tablets',
                title: "REDMI",
                imgsrc: "https://m.media-amazon.com/images/I/61PnHlc0HCL._SL1500_.jpg",
                amazonlink: "https://www.amazon.com/dp/B08L8NGB6S",
                description: "REDMI PAD PRO 5G",
                price:'69999',
                },
];
export default Data;